### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2779: character maps to <undefined>

### ISSUE THREAD

**Issue by Julit0Jr** [omidrohanian/irony_detection#1]
I tried running the feature_generator_TaskA.ipynb and it gave me this error.

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-15-22269c5d4f3f> in <module>()
          1 if TRAIN:
          2     dataset='../datasets/train/SemEval2018-T3-train-taskA_emoji.txt'
----> 3     corpus, _ = parse_dataset(dataset)
         4     corpus_preprocessed = json.load(open('../extra_resources/train_preprocessed.txt','r'))
         5 else:

~\Documents\Special Problem\198.2\irony_detection\subtaskA\load.py in parse_dataset(dataset)
         5     dataset_name = dataset.lower()
         6     with open(dataset, 'r') as data_in:
----> 7         for line in data_in:
         8             if not line.lower().startswith("tweet index"):      # discard first line if it contains metadata
         9                 line = line.rstrip()    # remove trailing whitespace

~\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
        21 class IncrementalDecoder(codecs.IncrementalDecoder):
        22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        24 
        25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2779: character maps to <undefined>

**Comment by omidrohanian** [comment]
What Python version are you using? I just ran this and it works without any errors on Python 3.5.2. Try explicitly passing an encoding argument (`encoding="utf8"` for example).
