### ISSUE TITLE
Recursive Feature Elimination leaves out contrast

### ISSUE THREAD

**Issue by ReinierKoops** [omidrohanian/irony_detection#5]
Hi, for a uni-project, I am trying to reproduce the paper and see if I am able to get the same results.
I picked your paper because I liked the paper and it seemed quite accessible, seeing everything is readily available on GitHub, which is really nice!

I have run the project multiple times, mimicking your setup as closely as possible. However, I am unable to get the 13 features as mentioned in your paper. I am only getting 12 as selected by RFEC (leaving out the feature contrast). I have tried on multiple environments (a couple of windows and one mac). It seems to be related to the "train_feats_taskA.npy"-file when I regenerate it. If I don't regenerate it I will have the same set of features as mentioned in your paper. 

I have thought of it being related to using a newer version of Stanford CoreNLP and the other packages, however, I thought maybe could shed some light on this. Do you maybe have a suggestion on what this could be related to? 

The code jupyter notebook "feature_generator_TaskA.ipynb" is the same as your repo.

**Comment by omidrohanian** [comment]
@ReinierKoops Hi, and thanks for your interest in the repo. 

It's strange indeed that the feature `contrast` doesn't show up at all in the top features. We should have specified the exact versions of all the dependencies used, so you could have tried it with the exact same setup. Apologies for that. As the is project is from two years ago, I am not too fresh on all the details and unfortunately too busy at the moment to dig into this further. 

My suggestions would be to try an earlier version of  Stanford CoreNLP. Also, try the 12 features plus `contrast` and see whether at least that particular feature set reproduces the results or not. 

RFECV uses 10-fold CV to rank the features, and it could be a bit unstable in different runs unless you specify a random state seed. Using different random seeds might also be good to try. 

Let me know if you couldn't figure it out and whether there is some serious inconsistency and I will analyse the code as soon as I can.

**Comment by ReinierKoops** [comment]
@omidrohanian Thank you for your suggestions! I will have a look at what you mentioned and will let you know if it doesn't work out :)
